name: BetterStructures
version: '2.1.2'
main: com.magmaguy.betterstructures.BetterStructures
api-version: 1.21.5
depend: [ FastAsyncWorldEdit ]
softdepend:
  - FastAsyncWorldEdit
  - Terralith
  - Iris
  - TerraformGenerator
author: vortexthedev

commands:
  bs:
    description: Main command